<template>
  <div class="dark-theme">
    <div class="content">
      <h1 class="page-title">YOUR FIRST BITCOIN WALLET</h1>

      <!-- Education intro -->
      <div class="intro-section">
        <p>
          Bitcoin lets you be your own bank — no middleman, no account to freeze, no permission
          needed. The key to this is <strong>self-custody</strong>.
        </p>
        <p>
          Self-custody means holding your own Bitcoin, and holding your own Bitcoin means holding
          your own <strong>seed phrase</strong>: 12 random words generated by your wallet that are
          the master key to all your funds.
        </p>
        <div class="seed-explainer">
          <p class="seed-label">Example seed phrase (never use this one):</p>
          <p class="seed-words">
            radar &nbsp; butter &nbsp; valley &nbsp; trumpet &nbsp; mirror &nbsp; giant &nbsp;
            ocean &nbsp; candle &nbsp; forest &nbsp; clock &nbsp; zebra &nbsp; lantern
          </p>
          <p>
            These 12 words — in the correct order — can restore your entire wallet on any device,
            anywhere in the world, at any time.
          </p>
        </div>
        <div class="key-rules">
          <p><strong>Before you touch any app, understand these rules:</strong></p>
          <ul>
            <li>Whoever holds the seed phrase holds the Bitcoin.</li>
            <li>If you lose your seed phrase, no one can recover your funds — ever.</li>
            <li>
              If anyone else sees your seed phrase, they can take everything — immediately.
            </li>
            <li>
              Your seed phrase should never exist digitally: no photos, no cloud, no notes app.
            </li>
          </ul>
          <p class="rule-footer">Write it on paper. Store it somewhere safe. That's it.</p>
        </div>
        <p class="scroll-cta">
          Read through all six steps below. The wallet download links are at the bottom.
        </p>
      </div>

      <!-- Step 1 -->
      <div class="step-section">
        <div class="step-header">
          <span class="step-number">1</span>
          <h3>Download and Install</h3>
        </div>
        <ol>
          <li>
            Visit
            <a href="https://bluewallet.io/" target="_blank" rel="noopener noreferrer"
              >bluewallet.io</a
            >.
          </li>
          <li>Download BlueWallet for your device (iOS or Android).</li>
          <li>Install and open the app.</li>
        </ol>
      </div>

      <!-- Step 2 -->
      <div class="step-section">
        <div class="step-header">
          <span class="step-number">2</span>
          <h3>Create a New Wallet</h3>
        </div>
        <ol>
          <li>Tap <strong>"Add a wallet"</strong> and choose a name for your wallet.</li>
          <li>
            Select <strong>"Bitcoin"</strong> for long-term storage.
            <span class="aside">(You can learn about Lightning later.)</span>
          </li>
          <li>Tap <strong>"Create"</strong> to generate your wallet.</li>
        </ol>
      </div>

      <!-- Step 3 — most important -->
      <div class="step-section highlight">
        <div class="step-header">
          <span class="step-number">3</span>
          <h3>Secure Your Wallet <span class="most-important">(MOST IMPORTANT)</span></h3>
        </div>
        <ol>
          <li>BlueWallet will generate <strong>12 secret words</strong> (your seed phrase).</li>
          <li>
            These 12 words <strong>are</strong> your Bitcoin. If you lose them, you lose access.
          </li>
          <li>
            <strong>Write them down on paper</strong> and store them in a secure place.
          </li>
          <li>Confirm the words by following the app's instructions.</li>
        </ol>
        <div class="do-not-box">
          <p class="do-not-title">DO NOT:</p>
          <ul>
            <li>Share them with anyone.</li>
            <li>Store them in the cloud or take a photo.</li>
            <li>Enter them into any website or app besides BlueWallet.</li>
          </ul>
        </div>
      </div>

      <!-- Step 4 -->
      <div class="step-section">
        <div class="step-header">
          <span class="step-number">4</span>
          <h3>Set a Wallet Password</h3>
        </div>
        <ol>
          <li>
            Go to <strong>Settings › Security</strong> and set a strong password.
          </li>
          <li>Enable biometric login (optional) for easier access.</li>
          <li>Turn on <strong>Advanced Mode</strong> for extra security features.</li>
        </ol>
      </div>

      <!-- Step 5 -->
      <div class="step-section">
        <div class="step-header">
          <span class="step-number">5</span>
          <h3>Receive Bitcoin</h3>
        </div>
        <ol>
          <li>Tap <strong>"Receive"</strong> and copy your Bitcoin address.</li>
          <li>Use this address to receive Bitcoin from an exchange or another wallet.</li>
          <li>Verify transactions in the Transactions tab.</li>
        </ol>
      </div>

      <!-- Step 6 -->
      <div class="step-section">
        <div class="step-header">
          <span class="step-number">6</span>
          <h3>Send Bitcoin</h3>
        </div>
        <ol>
          <li>Tap <strong>"Send"</strong> and paste the recipient's Bitcoin address.</li>
          <li>
            Adjust the network fee
            <span class="aside">(higher fee = faster confirmation)</span>.
          </li>
          <li>Double-check the details and confirm the transaction.</li>
        </ol>
      </div>

      <!-- How to get your first Bitcoin -->
      <div class="info-section">
        <h3>How to Get Your First Bitcoin</h3>
        <p>Ranked best to worst:</p>
        <ol>
          <li>
            Earn bitcoin for goods and services at events like <RouterLink to="/reunion">Reunion Festival</RouterLink> in Saskatoon or win bitcoin at places like the 
            <RouterLink to="/bitcoinblockparty">Bitcoin Block Party</RouterLink> in Vancouver.          
          </li>
          <li>
            Buy bitcoin from a trusted peer for cash through local connections at
            <RouterLink to="/bitcoinmeetup">Bitcoin Meetup</RouterLink>.
          </li>
          <li>
            Attend a public bitcoin meetup to win bitcoin:
            <RouterLink to="/bitcoinmeetup">festivall.ca/bitcoinmeetup</RouterLink>.
          </li>
          <li>
            Use a decentralized exchange like
            <a href="https://bisq.network" target="_blank" rel="noopener noreferrer">BISQ</a>.
          </li>
          <li>
            Less Preferred: Buy bitcoin from a regulated
            <a
              href="https://en.wikipedia.org/wiki/Know_your_customer"
              target="_blank"
              rel="noopener noreferrer"
              >KYC exchange</a
            >
            using your ID, like
            <a href="https://shakepay.com" target="_blank" rel="noopener noreferrer">Shakepay</a>
            or
            <a href="https://bullbitcoin.com" target="_blank" rel="noopener noreferrer"
              >Bull Bitcoin</a
            >.
          </li>
        </ol>
      </div>

      <!-- Want to spend -->
      <div class="info-section">
        <h3>Want to Spend Your Bitcoin?</h3>
        <p>
          Spend it at places like the
          <RouterLink to="/bitcoinblockparty">Bitcoin Block Party</RouterLink>
          and
          <RouterLink to="/reunion">Reunion Festival</RouterLink>
          to support circular Bitcoin commerce.
        </p>
      </div>

      <!-- Final Notes -->
      <div class="final-notes">
        <h3>Final Notes</h3>
        <ul>
          <li>Self-custody means <strong>you</strong> are responsible for your Bitcoin.</li>
          <li>Test with a small amount before sending large transactions.</li>
          <li>Regularly back up your seed phrase in multiple safe locations.</li>
          <li>
            Consider a hardware wallet for larger amounts —
            <a href="https://coinkite.com" target="_blank" rel="noopener noreferrer"
              >coinkite.com</a
            >.
          </li>
          <li>Do not get distracted by other "coins".</li>
        </ul>
        <p class="bitcoin-special">Bitcoin is special. There is no second best.</p>
      </div>

      <!-- Wallet Software CTA -->
      <div class="wallet-cta">
        <h2>Get the Wallet</h2>

        <div class="wallet-group">
          <h3 class="wallet-group-title">BlueWallet <span class="wallet-tag">Mobile</span></h3>
          <p>Free, open-source, and self-custodial. Best for everyday use on your phone.</p>
          <a
            href="https://apps.apple.com/app/bluewallet-bitcoin-wallet/id1376878040"
            target="_blank"
            rel="noopener noreferrer"
            class="wallet-btn"
            >Download for iOS</a
          >
          <a
            href="https://play.google.com/store/apps/details?id=io.bluewallet.bluewallet"
            target="_blank"
            rel="noopener noreferrer"
            class="wallet-btn"
            >Download for Android</a
          >
          <p class="verify-note">
            Verify at
            <a href="https://bluewallet.io/" target="_blank" rel="noopener noreferrer"
              >bluewallet.io</a
            >
          </p>
        </div>

        <div class="wallet-divider"></div>

        <div class="wallet-group">
          <h3 class="wallet-group-title">Sparrow Wallet <span class="wallet-tag">Desktop</span></h3>
          <p>
            Advanced desktop wallet for Windows, Mac, and Linux. Excellent for privacy, coin
            control, and connecting to your own node.
          </p>
          <a
            href="https://sparrowwallet.com/download/"
            target="_blank"
            rel="noopener noreferrer"
            class="wallet-btn"
            >Download Sparrow</a
          >
          <p class="verify-note">
            Verify at
            <a href="https://sparrowwallet.com/" target="_blank" rel="noopener noreferrer"
              >sparrowwallet.com</a
            >
          </p>
        </div>
      </div>

      <!-- Bitcoin Meetup -->
      <div class="meetup-section">
        <h3>Need More Guidance?</h3>
        <p>
          Join a free workshop —
          <RouterLink to="/bitcoinmeetup">festivall.ca/bitcoinmeetup</RouterLink>
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { onMounted } from 'vue'
import { logEvent } from 'firebase/analytics'
import { reunion_analytics } from '@/firebase'

onMounted(() => {
  logEvent(reunion_analytics, 'page_view', {
    page_title: 'Bitcoin Wallet Guide',
    page_location: window.location.href
  })
})
</script>

<style scoped>
.dark-theme {
  background-color: #121212;
  color: #ffffff;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
  padding: 2rem;
  min-height: 100vh;
}

.content {
  width: 80vw;
  max-width: 800px;
  padding: 1.5rem;
  border: 1px solid #444;
  border-radius: 15px;
  background-color: #1e1e1e;
  display: flex;
  flex-direction: column;
  align-items: center;
}

/* Header */
.page-title {
  color: var(--bitcoin-orange);
  text-shadow: 0px 0px 10px rgba(247, 147, 26, 0.4);
  font-size: 1.8rem;
  margin-bottom: 1.5rem;
  letter-spacing: 0.05em;
}

/* Intro */
.intro-section {
  width: 100%;
  margin-bottom: 2rem;
  text-align: left;
  line-height: 1.7;
}

.intro-section p {
  margin-bottom: 1rem;
}

.seed-explainer {
  background-color: #2a2a2a;
  border: 1px solid #555;
  border-radius: 10px;
  padding: 1.2rem 1.5rem;
  margin: 1.5rem 0;
}

.seed-label {
  font-size: 0.85rem;
  color: #aaa;
  margin-bottom: 0.5rem !important;
}

.seed-words {
  font-family: monospace;
  color: var(--bitcoin-orange);
  font-size: 1rem;
  letter-spacing: 0.03em;
  margin-bottom: 1rem !important;
  line-height: 1.8;
}

.key-rules {
  background-color: #1a1a1a;
  border-left: 3px solid var(--bitcoin-orange);
  border-radius: 0 8px 8px 0;
  padding: 1rem 1.5rem;
  margin: 1.5rem 0;
}

.key-rules ul {
  margin: 0.75rem 0;
  padding-left: 1.25rem;
}

.key-rules li {
  margin-bottom: 0.4rem;
}

.rule-footer {
  margin-top: 0.75rem !important;
  color: var(--bitcoin-orange);
  font-weight: bold;
}

.scroll-cta {
  color: #aaa;
  font-style: italic;
  margin-top: 0.5rem;
}

/* Steps */
.step-section {
  width: 100%;
  margin-bottom: 1.5rem;
  border: 1px solid #444;
  border-radius: 10px;
  padding: 1.25rem 1.5rem;
  text-align: left;
}

.step-section.highlight {
  border-color: var(--bitcoin-orange);
  background-color: #211900;
}

.step-header {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 1rem;
}

.step-number {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  min-width: 36px;
  border-radius: 50%;
  background-color: var(--bitcoin-orange);
  color: #000;
  font-weight: bold;
  font-size: 1rem;
}

.step-header h3 {
  margin: 0;
  color: #fff;
  font-size: 1.1rem;
}

.most-important {
  color: var(--bitcoin-orange);
  font-size: 0.85rem;
}

.step-section ol {
  margin: 0;
  padding-left: 1.4rem;
}

.step-section li {
  margin-bottom: 0.5rem;
  line-height: 1.6;
}

.aside {
  color: #999;
  font-size: 0.9rem;
}

.do-not-box {
  margin-top: 1rem;
  background-color: #2d1a1a;
  border: 1px solid #c0392b;
  border-radius: 8px;
  padding: 1rem 1.25rem;
}

.do-not-title {
  color: #e74c3c;
  font-weight: bold;
  margin-bottom: 0.5rem;
}

.do-not-box ul {
  padding-left: 1.25rem;
  margin: 0;
}

.do-not-box li {
  margin-bottom: 0.4rem;
  color: #ffaaaa;
}

/* Info sections */
.info-section {
  width: 100%;
  margin-bottom: 1.5rem;
  border: 1px solid #444;
  border-radius: 10px;
  padding: 1.25rem 1.5rem;
  text-align: left;
}

.info-section h3 {
  color: var(--bitcoin-orange);
  margin-bottom: 0.75rem;
}

/* Final notes */
.final-notes {
  width: 100%;
  margin-bottom: 1.5rem;
  border: 1px solid #555;
  border-radius: 10px;
  padding: 1.25rem 1.5rem;
  text-align: left;
  background-color: #1a1a1a;
}

.final-notes h3 {
  margin-bottom: 0.75rem;
  color: #ccc;
}

.final-notes ul {
  padding-left: 1.25rem;
  margin-bottom: 1rem;
}

.final-notes li {
  margin-bottom: 0.5rem;
  line-height: 1.6;
}

.bitcoin-special {
  text-align: center;
  font-weight: bold;
  color: var(--bitcoin-orange);
  font-size: 1.05rem;
  margin-top: 0.75rem;
}

/* Wallet CTA */
.wallet-cta {
  width: 100%;
  margin-bottom: 1.5rem;
  border: 2px solid var(--bitcoin-orange);
  border-radius: 12px;
  padding: 1.75rem 1.5rem;
  background-color: #1c1400;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.75rem;
}

.wallet-cta h2 {
  color: var(--bitcoin-orange);
  margin-bottom: 0.5rem;
}

.wallet-group {
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.65rem;
}

.wallet-group-title {
  color: #fff;
  margin: 0;
  font-size: 1.1rem;
  display: flex;
  align-items: center;
  gap: 0.6rem;
}

.wallet-tag {
  font-size: 0.7rem;
  font-weight: normal;
  background-color: #333;
  color: #aaa;
  border-radius: 4px;
  padding: 0.15rem 0.5rem;
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

.wallet-divider {
  width: 60%;
  height: 1px;
  background-color: #444;
  margin: 0.5rem 0;
}

.wallet-btn {
  display: inline-block;
  padding: 0.7rem 2rem;
  background-color: var(--bitcoin-orange);
  color: #000;
  border-radius: 8px;
  font-weight: bold;
  text-decoration: none;
  font-size: 1rem;
  transition: opacity 0.2s;
  width: 100%;
  max-width: 320px;
  text-align: center;
}

.wallet-btn:hover {
  opacity: 0.85;
}

.verify-note {
  font-size: 0.82rem;
  color: #888;
  text-align: center;
}

/* Meetup */
.meetup-section {
  width: 100%;
  text-align: center;
  padding: 1.25rem;
  border: 1px solid #444;
  border-radius: 10px;
  margin-bottom: 0.5rem;
}

.meetup-section h3 {
  margin-bottom: 0.5rem;
  color: #ccc;
}

/* Links */
a {
  color: var(--bitcoin-orange);
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

@media (max-width: 600px) {
  .dark-theme {
    padding: 1rem 0.5rem;
  }

  .content {
    width: 95vw;
    padding: 1rem 0.75rem;
  }

  .step-section,
  .info-section,
  .final-notes {
    padding: 1rem 0.9rem;
  }

  .wallet-cta {
    padding: 1.25rem 0.9rem;
  }

  .seed-explainer,
  .key-rules {
    padding: 1rem 0.9rem;
  }
}
</style>
