name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and build
        run: npm ci && npm run build
        env:
          VITE_APP_REUNION_API_KEY: ${{ secrets.VITE_APP_REUNION_API_KEY }}
          VITE_APP_REUNION_AUTH_DOMAIN: ${{ secrets.VITE_APP_REUNION_AUTH_DOMAIN }}
          VITE_APP_REUNION_PROJECT_ID: ${{ secrets.VITE_APP_REUNION_PROJECT_ID }}
          VITE_APP_REUNION_STORAGE_BUCKET: ${{ secrets.VITE_APP_REUNION_STORAGE_BUCKET }}
          VITE_APP_REUNION_MESSAGING_SENDER_ID: ${{ secrets.VITE_APP_REUNION_MESSAGING_SENDER_ID }}
          VITE_APP_REUNION_APP_ID: ${{ secrets.VITE_APP_REUNION_APP_ID }}
          VITE_APP_REUNION_MEASUREMENT_ID: ${{ secrets.VITE_APP_REUNION_MEASUREMENT_ID }}
          VITE_APP_FESTIVALL_API_KEY: ${{ secrets.VITE_APP_FESTIVALL_API_KEY }}
          VITE_APP_FESTIVALL_AUTH_DOMAIN: ${{ secrets.VITE_APP_FESTIVALL_AUTH_DOMAIN }}
          VITE_APP_FESTIVALL_PROJECT_ID: ${{ secrets.VITE_APP_FESTIVALL_PROJECT_ID }}
          VITE_APP_FESTIVALL_STORAGE_BUCKET: ${{ secrets.VITE_APP_FESTIVALL_STORAGE_BUCKET }}
          VITE_APP_FESTIVALL_MESSAGING_SENDER_ID: ${{ secrets.VITE_APP_FESTIVALL_MESSAGING_SENDER_ID }}
          VITE_APP_FESTIVALL_APP_ID: ${{ secrets.VITE_APP_FESTIVALL_APP_ID }}
          VITE_APP_FESTIVALL_MEASUREMENT_ID: ${{ secrets.VITE_APP_FESTIVALL_MEASUREMENT_ID }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FESTIVALL_6969 }}'
          channelId: live
          projectId: festivall-6969
